### PR TITLE
Fix a small bug in NetworkingRouter

### PR DESCRIPTION
**Pull request by creativedrewy**
## Description
Prior to this fix, in `NetworkingRouter.kt`, when an error response comes in, the class would still try and read from `inputStream`. In the error case, that may not exist, so it throws an exception.

## Work Completed
This PR fixes the bug in NetworkingRouter. It mirrors a fix that was made by @Funkatronics in the other metaplex kt lib.

### CODE REVIEW

**Review by Funkatronics — APPROVED** [review]

**Comment by Funkatronics** [comment]
I give my blessing but want to let @ajamaica take the final call

**Comment by Funkatronics** [comment]
this mirrors the fix made [here](https://github.com/metaplex-foundation/metaplex-android/pull/101/files)

**Comment by creativedrewy** [comment]
@ajamaica can you re-run the CI

**Comment by ajamaica** [comment]
Hey! I was on a flight. Sorry for not seeing this.

**Review by ajamaica — APPROVED** [review]
I see the bug. Thanks for the fix Now i think we need to handle the resources better.

**Comment by Funkatronics** [comment]
Thanks Arturo! Do you know whats up with the CI? lmk if you need some help with that

**Comment by ajamaica** [comment]
Not sure. I am giving time for this next months.

**Pull request merged**
